name = "bookmark-bot"
main = "build/worker/shim.mjs"
compatibility_date = "2023-01-20"


[vars]
WORKERS_RS_VERSION = "0.0.14"

[build]
command = "cargo install -q worker-build && worker-build --release"